##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-crypto-pvc
  namespace: {{ $.Values.metadata.namespace }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}    
  labels:
    {{ include "labels.pvc" . | nindent 2 }}  
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-pvc
  namespace: {{ $.Values.metadata.namespace }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}    
  labels:
    {{ include "labels.pvc" . | nindent 2 }}     
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}

