apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-generate-ambassador-certs-job
  namespace: carrier-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-generate-ambassador-certs-job
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tlscerts-gen
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    name: "carrier"
    metadata:
      namespace: carrier-quo
    image:
      initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
      certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    vault:
      address: 
      role: vault-role
      authpath: quorumcarrier
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/carrier-quo
      retries: 30
      type: hashicorp
    subjects:
      root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
    opensslVars:
      domain_name: "carrier.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_api: "carrierapi.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_web: "carrierweb.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_tessera: "carrier-tessera.carrier-quo"
      clientport: 8888
