---
#helm install supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
#helm upgrade supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    network: corda-enterprise
  proxy:
    provider: "ambassador"
    externalUrlSuffix: test.blockchaincloud.com
storage:
  size: 1Gi
  dbSize: 5Gi
  allowedTopologies:
    enabled: false

settings:
  removeKeysOnDelete: true # this will erase keys

tls:
  enabled: true
