---
#helm install notary -f values/noproxy-and-novault/notary.yaml -n supplychain-ns corda-node 
#helm upgrade notary -f values/noproxy-and-novault/notary.yaml -n supplychain-ns corda-node
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
  proxy:
    provider: "ambassador"
    externalUrlSuffix: test.blockchaincloud.com
image:
  notary:
    repository: corda/corda-enterprise
    tag: 4.10.3-zulu-openjdk8-alpine

network:
  creds:
    truststore: password

# tls:
#   nameOverride: notary   # should match the release name
#   enabled: true

nodeConf:
  legalName: "O=Notary,OU=Notary,L=London,C=GB"
  notary:
    validating: true
    serviceLegalName: "O=Notary,OU=Notary Service,L=London,C=GB"
  doormanPort: 443
  networkMapPort: 443
  doormanDomain: cenm-doorman.test.blockchaincloud.com
  networkMapDomain: cenm-nms.test.blockchaincloud.com
  networkMapURL: https://cenm-nms.test.blockchaincloud.com
  doormanURL: https://cenm-doorman.test.blockchaincloud.com
