##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

##############################################################################################
# This role creates the deployment files for node and pushes them to repository
##############################################################################################

- name: "Setup primary init with network-service org"
  include_role:
    name: init
  vars:
    build_path: "./build"
    init_type: "secondary_init"
    values_dir: "./build/{{ component_ns }}"
    
# Create deployment file for node node
- name: Create node deployment file
  include_role: 
    name: create/helm_component
  vars:    
    type: "corda_node"
    component_name: "{{ node.name | lower }}"
    nms_url: "{{ network | json_query('network_services[?type==`networkmap`].uri') | first }}"
    doorman_url: "{{ network | json_query('network_services[?type==`doorman`].uri') | first }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: node

# Git Push: Push the deployment files for node
- name: Push node deployment files
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing node deployment file for node"
