apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: channel-cfab-allchannel
  namespace: cfab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: channel-cfab-allchannel
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-channel-create   
  values:
    metadata:
      namespace: cfab-net
      network:
        version: 2.2.2
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.cfab-net:7051
      localmspid: cfabMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://demo.sau99.dev.aws.blockchaincloudpoc-develop.com
      authpath: fabric-saicfab-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/cfab-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/cfab-net/orderer 
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    channel:
      name: allchannel
    orderer:
      address: orderer7.hf.demo.aws.blockchaincloudpoc.com:8443
    channeltx: |-
      CqkDChgKFggCGgYIqs+ArQYiCmFsbGNoYW5uZWwSjAMKiQMKCmFsbGNoYW5uZWwSLhIcCgtBcHBs
      aWNhdGlvbhINEgsKB2NmYWJNU1ASABoOCgpDb25zb3J0aXVtEgAaygISngIKC0FwcGxpY2F0aW9u
      Eo4CCAESCwoHY2ZhYk1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMi
      IgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFk
      bWlucxACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRt
      aW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlu
      cyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRp
      dW0SGRIXChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0=
