apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cfab-cacerts-job
  namespace: cfab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cfab-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: cfab
      component_name: cfab-net
      namespace: cfab-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: fabric-saicfab
      secretcryptoprefix: secretsv2/data/cfab/peerOrganizations/cfab-net/ca
      secretcredentialsprefix: secretsv2/data/cfab/credentials/cfab-net/ca/cfab
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Carrier/CN=ca.cfab-net
