apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-cfab-peer0
  namespace: cfab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-cfab-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-channel-join
  values:
    metadata:
      namespace: cfab-net
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.cfab-net.hf.demo.aws.blockchaincloudpoc.com:8443
      localmspid: cfabMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://demo.sau99.dev.aws.blockchaincloudpoc-develop.com
      authpath: fabric-saicfab-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/cfab-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/cfab-net/orderer
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer7.hf.demo.aws.blockchaincloudpoc.com:8443
