apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cfab-peer0
  namespace: cfab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cfab-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-peernode    
  values:
    metadata:
      namespace: cfab-net
      images:
        couchdb:  ghcr.io/hyperledger/bevel-fabric-couchdb:2.5.4
        peer:  ghcr.io/hyperledger/bevel-fabric-peer:2.5.4
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

        
    peer:
      name: peer0
      gossippeeraddress: peer0.cfab-net.hf.demo.aws.blockchaincloudpoc.com:443
      gossipexternalendpoint: peer0.cfab-net.hf.demo.aws.blockchaincloudpoc.com:443
      localmspid: cfabMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.5.4
      couchdb:
        username: cfab-user
      configpath: conf/peer0_cfab_core.yaml
      core: |-
        

    storage:
      peer:
        storageclassname: cfab-bevel-storageclass
        storagesize: 512Mi
      couchdb:
        storageclassname: cfab-bevel-storageclass
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: fabric-saicfab
      secretprefix: secretsv2/data/cfab/peerOrganizations/cfab-net/peers/peer0.cfab-net
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/cfab/credentials/cfab-net/couchdb/cfab?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
        metrics: 
          enabled: False
          clusteripport: 9443     
    proxy:
      provider: "haproxy"
      external_url_suffix: hf.demo.aws.blockchaincloudpoc.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.25
