apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplytest-cacerts-job
  namespace: supplytest-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplytest-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: supplytest
      component_name: supplytest-net
      namespace: supplytest-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: fabric-saisupplytest
      secretcryptoprefix: secretsv2/data/supplytest/ordererOrganizations/supplytest-net/ca
      secretcredentialsprefix: secretsv2/data/supplytest/credentials/supplytest-net/ca/supplytest
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplytest-net
