apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: validator2-ambassador-job
  namespace: chainsupply-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: validator2-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tlscert-cert-gen
    sourceRef:
      kind: GitRepository
      name: flux-env-type
      namespace: flux-env-type
  values:
    metadata:
      name: validator2-ambassador-job
      namespace: chainsupply-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: validator2
      clientport: 8888
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besuchainsupply
      rootcasecret: data/chainsupply-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: data/chainsupply-bes/crypto/validator2/tls
      role: vault-role
      serviceaccountname: vault-auth
      type: hashicorp
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: validator2.test.besu.blockchaincloudpoc.com
      domain_name_priv: validator2.chainsupply-bes
      domain_name_tessera: validator2-tessera.chainsupply-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2

    labels:
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
