dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - storage
    version: ~1.0.0
  - name: corda-certs-gen
    alias: tls
    repository: "file://../../../r3-corda/charts/corda-certs-gen"
    tags:
      - bevel
    version: ~1.0.0
    condition: tls.enabled
