global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    network: substrate
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain" 
    role: vault-role
proxy:
  provider: ambassador 

config:
  nodeHost: member-1-substrate-node
  