##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# helm install validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node
# helm upgrade validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node

global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    network: substrate
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    role: vault-role

node:
  isBootnode:
    enabled: false # false | true
    bootnodeName: 
    bootnodeAddr: 
    bootnodePort: 
    role: validator # full | validator

proxy:
  provider: ambassador  # none | ambassador
  external_url: test.yourdomain.com  #specify the endpoint for the ambassador url 
