apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cfab-net-ca-tools
  namespace: cfab-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: cfab-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric-sai
        namespace: flux-fabric-sai
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: cfab-net
      name: ca-tools
      component_type: peer
      org_name: cfab
      proxy: haproxy
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: cfab-aws-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://demo.sau99.dev.aws.blockchaincloudpoc-develop.com
      authpath: fabric-saicfab-net-auth
      secretusers: secretsv2/data/crypto/peerOrganizations/cfab-net/users
      secretorderer: secretsv2/data/crypto/peerOrganizations/cfab-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/cfab-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/cfab-net/orderer/tls
      secretcert: secretsv2/data/crypto/peerOrganizations/cfab-net/ca?ca.cfab-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/cfab-net/ca?cfab-net-CA.key
      secretcouchdb: secretsv2/data/credentials/cfab-net/couchdb/cfab
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/cfab-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: hf.demo.aws.blockchaincloudpoc.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.cfab-net:7054

    orderers:
      name: orderer7-orderer8-orderer9-
    orderers_info:
      - name: orderer7
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4akNDQVppZ0F3SUJBZ0lVQmFEamlyaERlQTNzeEdEMXRhcmNvTGJ3a2dNd0NnWUlLb1pJemowRUF3SXcKVnpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlF3RWdZRFZRUUREQXRqWVM1elptRmlMVzVsZERBZUZ3MHlOREF4Ck1URXhOekkzTlRCYUZ3MHlOakV3TXpFeE56STNOVEJhTUZjeEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRFZRUUkKREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIVDNKa1pYSmxjakVVTUJJRwpBMVVFQXd3TFkyRXVjMlpoWWkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU1VVbEtkClpxai9ZdVYvWXplcFc3N24wL21IM3h3ZlV3STlHS1RYR3Y3WFYvbXg4bW5RV2I5NlFmY29nT2JJb3pLMno3NTQKYWx5U2owMWtQRWNMdzdnam8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQgpwakFkQmdOVkhRNEVGZ1FVSFM2NTBZdW5idDFkbkRUV29UMlcwaFltKzdJd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBSUoreHpqR1FJeXFrS2dSYVJvZzhDVk84UjJlZys5d2VJTkk2SlZVczNobUFpQjBJWi9ndk5rVjRUR08KMFdOLzl3cUZOc3ZJRjZiOG8vZzVWQU45VGRhaWdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
      - name: orderer8
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4akNDQVppZ0F3SUJBZ0lVQmFEamlyaERlQTNzeEdEMXRhcmNvTGJ3a2dNd0NnWUlLb1pJemowRUF3SXcKVnpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlF3RWdZRFZRUUREQXRqWVM1elptRmlMVzVsZERBZUZ3MHlOREF4Ck1URXhOekkzTlRCYUZ3MHlOakV3TXpFeE56STNOVEJhTUZjeEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRFZRUUkKREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIVDNKa1pYSmxjakVVTUJJRwpBMVVFQXd3TFkyRXVjMlpoWWkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU1VVbEtkClpxai9ZdVYvWXplcFc3N24wL21IM3h3ZlV3STlHS1RYR3Y3WFYvbXg4bW5RV2I5NlFmY29nT2JJb3pLMno3NTQKYWx5U2owMWtQRWNMdzdnam8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQgpwakFkQmdOVkhRNEVGZ1FVSFM2NTBZdW5idDFkbkRUV29UMlcwaFltKzdJd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBSUoreHpqR1FJeXFrS2dSYVJvZzhDVk84UjJlZys5d2VJTkk2SlZVczNobUFpQjBJWi9ndk5rVjRUR08KMFdOLzl3cUZOc3ZJRjZiOG8vZzVWQU45VGRhaWdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
      - name: orderer9
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4akNDQVppZ0F3SUJBZ0lVQmFEamlyaERlQTNzeEdEMXRhcmNvTGJ3a2dNd0NnWUlLb1pJemowRUF3SXcKVnpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUlF3RWdZRFZRUUREQXRqWVM1elptRmlMVzVsZERBZUZ3MHlOREF4Ck1URXhOekkzTlRCYUZ3MHlOakV3TXpFeE56STNOVEJhTUZjeEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRFZRUUkKREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIVDNKa1pYSmxjakVVTUJJRwpBMVVFQXd3TFkyRXVjMlpoWWkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU1VVbEtkClpxai9ZdVYvWXplcFc3N24wL21IM3h3ZlV3STlHS1RYR3Y3WFYvbXg4bW5RV2I5NlFmY29nT2JJb3pLMno3NTQKYWx5U2owMWtQRWNMdzdnam8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQgpwakFkQmdOVkhRNEVGZ1FVSFM2NTBZdW5idDFkbkRUV29UMlcwaFltKzdJd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBSUoreHpqR1FJeXFrS2dSYVJvZzhDVk84UjJlZys5d2VJTkk2SlZVczNobUFpQjBJWi9ndk5rVjRUR08KMFdOLzl3cUZOc3ZJRjZiOG8vZzVWQU45VGRhaWdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2tleTEnLCAndmFsdWUnOiAndmFsdWUxJ30sIHsna2V5JzogJ2tleTInLCAndmFsdWUnOiAndmFsdWUyJ31dfSwgeyd1c2VyJzogTm9uZSwgJ2lkZW50aXR5JzogJ3VzZXIyJywgJ2F0dHJpYnV0ZXMnOiBbeydrZXknOiAna2V5MScsICd2YWx1ZSc6ICd2YWx1ZTEnfSwgeydrZXknOiAna2V5MycsICd2YWx1ZSc6ICd2YWx1ZTMnfV19XQ=="
      users_identities: user1-user2-
    checks:
      refresh_cert_value: False
      add_peer_value: False
