#helm install init -f values/noproxy-and-novault/init-sec.yaml -n manufacturer-ns corda-init
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: manufacturer
    secretEngine: secretsv2
    secretPrefix: "data/manufacturer"
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetesUrl: "https://yourkubernetes.com"

settings:
  # Flag to copy doorman and nms certs only when tls: true
  secondaryInit: true
