apiVersion:  helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriertessera
  namespace: carri1-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriertessera
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tessera-node
    sourceRef:
      kind: GitRepository
      name: flux-env-type
      namespace: flux-env-type
  values:
    replicaCount: 1
    metadata:
      namespace: carri1-bes
      labels:
    images:
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    tessera:
      name: carrier-tessera
      dbname: demodb
      dburl: "jdbc:mysql://carrier-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      url: "https://carrier.sai.dev.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "https://carrier-tessera:8888"
      othernodes:
        - url: https://carrier.test.besu.blockchaincloudpoc-develop.com
      trust: "TOFU"

      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: carrier-ambassador-certs
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      tmsecretpath: carri1-bes/crypto/carrier/tm
      secretprefix: data/carri1-bes/crypto/carrier
      serviceaccountname: vault-auth
      keyname: credentials
      type: hashicorp
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarri1
    proxy:
      provider: "ambassador"
      external_url: carrier.sai.dev.aws.blockchaincloudpoc-develop.com
      portTM: 443
    storage:
      storageclassname: carri1-aws-storageclass
      storagesize: 1Gi
      dbstorage: 1Gi

    labels:
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu

    metrics:
      enabled: False
      port: 9545
