apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carri1carriermember-node
  namespace: carri1-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carri1carriermember-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-member-node
    sourceRef:
      kind: GitRepository
      name: flux-env-type
      namespace: flux-env-type
  values:
    metadata:
      namespace: carri1-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://ca69b4d63ad585441e873e636c4604db494ba9112d289577aced327c118abd43ade493be20fcab7e684c9842e65130ecadefab0e3fe029e3f4b3f93bcc32f024@validator1.sai.dev.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://de567e9ba53745c553695cb2ac8b0de6cfd7d56f97ecce556a7d69b6c7baf7c686b7ebc1b9bf348f93cdaefa950da92062cab12b1fe7fdeae2e56bafe770a603@validator2.sai.dev.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://42b0861dd7cfa4d88aa507d132c8c24305d10c1b6e9b4d09fe9cbd763905e4649d1c43b92c93e1d7096bfd34b77e2b57f9e1f952aab658b1e985b3561181df61@validator3.sai.dev.aws.blockchaincloudpoc-develop.com:15014"
      - "enode://adc426993089ea9f6398e6b1b50f6bdde53e91c11e1475c3ea63190b32c303f3a0206b9f73bbe2532fe823d00a01a14fd2ad6d2c2c4b377e7b22de9794db9785@validator4.sai.dev.aws.blockchaincloudpoc-develop.com:15016"
      - "enode://bfc7f5396bd384c37555426d7400f86ecbcc8d2bd382ba63d95c8eba1360a245b15c686c165dab1b9c2f73476b9db288844e8d87953a81093b355e82f1979bfb@carrier.sai.dev.aws.blockchaincloudpoc-develop.com:15020"

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
    proxy:
      provider: ambassador
      external_url: sai.dev.aws.blockchaincloudpoc-develop.com
      p2p: 15020
      rpc: 80

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: carrier
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False

    tm:
      type: tessera
      tls: True
      url: "https://carrier-tessera.carri1-bes:8888"

    privacy:
      enabled: true
      public_key_file: /secrets/tm_key.pub
      tm_flag: true

    storage:
      storageclassname: carri1-aws-storageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      secretprefix: data/carri1-bes/crypto/carrier
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      type: hashicorp
      authpath: besucarri1

    genesis: 

   
    labels:  
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
 

    metrics:
      enabled: False
      port: 9545
