apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-tessera-job
  namespace: carri1-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrier-tessera-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tessera-key-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-bsk
      namespace: flux-bsk
  values:
    metadata:
      name: carrier-tessera-job
      namespace: carri1-bes
    peer:
      name: carrier
    image:
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besucarri1
      role: vault-role
      keyprefix: carri1-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: data/carri1-bes/crypto
      type: hashicorp

    labels:
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
