#helm install init -f values/noproxy-and-novault/init.yaml -n supplychain-ns corda-init
global:
  serviceAccountName: bevel-auth
  vault:
    type: kubernetes
    network: corda
  cluster:
    provider: aws
    cloudNativeServices: false
