apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturerdb
  annotations:
    fluxcd.io/automated: "false"
  namespace: manufacturer-ns
spec:
  releaseName: manufacturerdb
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/corda-h2
      sourceRef:
        kind: GitRepository
        name: flux-corda
        namespace: flux-corda
  values:
    replicaCount: 1
    nodeName: manufacturer
    metadata:
      namespace: manufacturer-ns
    image:
      containerName: ghcr.io/hyperledger/h2:2018
      imagePullSecret: regcred
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: manufacturer-bevel-storageclass
    service:
      type: NodePort
      p2p:
        port: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005
      tcp:
        port: 9101
        targetPort: 1521
      web:
        targetPort: 81
        port: 8080
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
