apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: manufacturer-ns
spec:
  releaseName: manufacturer-initial-registration
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/corda-node-initial-registration
      sourceRef:
        kind: GitRepository
        name: flux-corda
        namespace: flux-corda
  values:
    nodeName: manufacturer
    replicas: 1
    metadata:
      namespace: manufacturer-ns  
    image:
      containerName: ghcr.io/hyperledger/bevel-corda:4.9
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.corda.blockchaincloudpoc-develop.com
      networkmapCertAlias: networkmap.corda.blockchaincloudpoc-develop.com
    nodeConf:
      p2p:
        url: manufacturer.manufacturer-ns
        port: 10002
      ambassadorAddress: manufacturer.corda.blockchaincloudpoc-develop.com:15010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: manufacturerdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://manufacturerdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.corda.blockchaincloudpoc-develop.com
      doormanURL: https://doorman.corda.blockchaincloudpoc-develop.com
      compatibilityZoneURL:
      jarVersion: 4.9
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: manufactureroperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://98.64.226.131:20001
      role: vault-role
      authpath: cordamanufacturer
      serviceaccountname: vault-auth
      dbsecretprefix: secretsv4/data/manufacturer/manufacturer/credentials/database
      rpcusersecretprefix: secretsv4/data/manufacturer/manufacturer/credentials/rpcusers
      keystoresecretprefix: secretsv4/data/manufacturer/manufacturer/credentials/keystore
      certsecretprefix: secretsv4/data/manufacturer/manufacturer/certs
      retries: 10
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
