apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chainsupplyvalidator3validator-node
  namespace: chainsupply-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: chainsupplyvalidator3validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-validator-node
    sourceRef:
      kind: GitRepository
      name: flux-env-type
      namespace: flux-env-type
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://ca69b4d63ad585441e873e636c4604db494ba9112d289577aced327c118abd43ade493be20fcab7e684c9842e65130ecadefab0e3fe029e3f4b3f93bcc32f024@validator1.sai.dev.aws.blockchaincloudpoc-develop.com:15010"
      - "enode://de567e9ba53745c553695cb2ac8b0de6cfd7d56f97ecce556a7d69b6c7baf7c686b7ebc1b9bf348f93cdaefa950da92062cab12b1fe7fdeae2e56bafe770a603@validator2.sai.dev.aws.blockchaincloudpoc-develop.com:15012"
      - "enode://42b0861dd7cfa4d88aa507d132c8c24305d10c1b6e9b4d09fe9cbd763905e4649d1c43b92c93e1d7096bfd34b77e2b57f9e1f952aab658b1e985b3561181df61@validator3.sai.dev.aws.blockchaincloudpoc-develop.com:15014"
      - "enode://adc426993089ea9f6398e6b1b50f6bdde53e91c11e1475c3ea63190b32c303f3a0206b9f73bbe2532fe823d00a01a14fd2ad6d2c2c4b377e7b22de9794db9785@validator4.sai.dev.aws.blockchaincloudpoc-develop.com:15016"
      - "enode://bfc7f5396bd384c37555426d7400f86ecbcc8d2bd382ba63d95c8eba1360a245b15c686c165dab1b9c2f73476b9db288844e8d87953a81093b355e82f1979bfb@carrier.sai.dev.aws.blockchaincloudpoc-develop.com:15020"

    metadata:
      namespace: chainsupply-bes
      labels:

    ambassador:
      external_url_suffix: sai.dev.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: sai.dev.aws.blockchaincloudpoc-develop.com
      p2p: 15014
      rpc: 80

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator3
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: chainsupply-aws-storageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      secretprefix: data/chainsupply-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besuchainsupply
      type: hashicorp

    genesis: 

   
    labels:  
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu

    metrics:
      enabled: False
      port: 9545    
