---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cenm
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: supplychain-cenm
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda-ent/charts/cenm
      sourceRef:
        kind: GitRepository
        name: flux-ent
        namespace: flux-ent
  values:
    global:
      serviceAccountName: bevel-auth
      cluster:
        provider: azure
        cloudNativeServices: false
      vault:
        type: hashicorp
        role: vault-role
        address: http://98.64.226.131:20001
        authPath: supplychain
        secretEngine: secretsv2
        secretPrefix: "data/supplychain"
        network: corda-enterprise
      proxy:
        provider: "ambassador"
        externalUrlSuffix: corda.blockchaincloudpoc-develop.com
    storage:
      size: 1Gi
      dbSize: 5Gi
      allowedTopologies:
        enabled: false

    settings:
      removeKeysOnDelete: true # this will erase keys

    tls:
      enabled: true
