##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
name: corda-certs-gen
description: "R3 Corda: Generates and stores TLS certificates for nodes and network services"
version: 1.0.1
appVersion: latest
keywords:
  - bevel
  - hyperledger
  - corda
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
