apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supplychain-nm
  namespace: supplychain-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-nm
  interval: 1m
  chart:
   spec:
    chart: platforms/r3-corda-ent/charts/cenm-networkmap
    sourceRef:
      kind: GitRepository
      name: flux-corh
      namespace: flux-corh
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: "azure"
        cloudNativeServices: false
      vault:
        type: hashicorp
        role: vault-role
        address: 
        authPath: "supplychain"
        secretEngine: secretsv2
        secretPrefix: "data/supplychain"
      proxy:
        provider: "ambassador"
        externalUrlSuffix: "corda.blockchaincloudpoc-develop.com"
      cenm:
        sharedCreds:
          truststore: {'truststore': 'trustpass', 'rootca': 'rootpassword', 'ssl': 'password'}
          keystore: {'keystore': 'cordacadevpass', 'idman': 'password', 'networkmap': 'password', 'subordinateca': 'password', 'rootca': 'password', 'tlscrlsigner': 'password'}
        identityManager:
          internal:
            port: 5052
          port: 10000
          revocation:
            port: 5053
        auth:
          port: 8081
        gateway:
          port: 8080
        zone:
          enmPort: 25000
        networkmap:
          internal:
            port: 5050
          port: 10000
    prefix: "supplychain-cenm"
    storage:
      size: 1Gi
      dbSize: 5Gi
      allowedTopologies:
        enabled: false

    database:
      driverClassName: "org.h2.Driver"
      jdbcDriver: ""
      url: "jdbc:h2:file:./h2/networkmap-manager-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
      user: "networkmap-db-user"
      password: "networkmap-db-password"
      runMigration: true

    nmapUpdate: false
    sleepTimeAfterError: 120
    baseDir: /opt/cenm
    
    adminListener:
      port: 6000
