apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cenm
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ent
spec:
  releaseName: supplychain-cenm
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda-ent/charts/cenm
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: corda-enterprise
        address: vault_addr
        authPath: devsupplychain
        secretEngine: secretsv2
        secretPrefix: "data/devsupplychain"
        role: vault-role
      proxy:
        provider: ambassador
        externalUrlSuffix: test.corda.blockchaincloudpoc.com
      cenm:
        sharedCreds:
          truststore: password
          keystore: password
        identityManager:
          port: 10000
          revocation:
            port: 5053
          internal:
            port: 5052
        auth:
          port: 8081 # 8081
          subject: CN=Test TLS Auth Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US
        gateway:
           port: 8080 # 8080
           subject: CN=Test TLS Gateway Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US
        zone:
          enm: 25000 # value to be set for enm
          admin: 12345 # value to be set for admin
          # enmPort: 25000 #zone.
          # adminPort: 12345
        networkmap:
          subject: CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US
          internal: 5050
          external: 10000
          admin_listener: 6000
    storage:
      size: 1Gi
      dbSize: 5Gi
      allowedTopologies:
        enabled: false
      settings:
        removeKeysOnDelete: true

    tls:
      enabled: true
    image:
      pullSecret:
      pullPolicy: IfNotPresent
      pki:
        repository: corda/enterprise-pkitool
        tag: 1.5.9-zulu-openjdk8u382
      hooks:
        repository: adopblockchaincloud0502.azurecr.io/bevel-build
        tag: jdk8-stable