apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ent
spec:
  releaseName: test
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda-ent/charts/enterprise-node
      sourceRef:
        kind: GitRepository
        name: flux-ent
        namespace: flux-ent
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: azure
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: corda
        role: vault-role
        address: http://98.64.226.131:20001
        authPath: entsupplychain
        secretEngine: secretsv2
        secretPrefix: "data/entsupplychain"
      proxy:
        provider: ambassador
        externalUrlSuffix: corda.blockchaincloudpoc-develop.com
        p2p: 15010
    storage:
      size: 1Gi
      dbSize: 2Gi
    image:
      pullSecret: regcred
      pullPolicy: IfNotPresent
      node:
        repository: corda/corda-enterprise
        tag: 4.10.3-zulu-openjdk8-alpine
      bevelAlpine:
        repository:  ghcr.io/hyperledger/bevel-alpine
        tag: latest

    network:
      creds:
        truststore: password
    tls:
      nameOverride: notary   # should match the release name
      enabled: false

    dataSourceProperties:
      dataSource:
        user: node-db-user
        password: node-db-password
        url: "jdbc:h2:file:./h2/node-persistence;DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0;LOCK_TIMEOUT=10000"
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource

  nodeConf:
    creds:
      truststore: cordacadevpass
      keystore: trustpass
    crlCheckSoftFail: true
    tlsCertCrlDistPoint: ""
    tlsCertCrlIssuer: ""
    devMode: false
    monitoring:
      enabled: true
      port: 8090
    allowDevCorDapps:
      enabled: true
    p2pPort: "10002" #10002
    rpc:
      port: "10003" #10003
      adminPort: "10005" #10005
      users:
      - name: node
        password: nodeP
        permissions: ALL
    ssh:
        enabled: true
        sshdPort: 2222
    removeKeysOnDelete: false
    legalName: O=Notary,OU=Notary2,L=London,C=GB #use peer-node level subject for legalName
  firewall:
    enabled: false
  cordApps: 
    #Provide if you want to provide jars in cordApps
    #Eg. getCordApps: true or false
    getCordApps: false
    jars: [{'jar': {'url': 'https://repo/path/cordapp1.jar'}}, {'jar': {'url': 'https://repo/path/cordapp2.jar'}}]
    mavenSecret: "maven-secrets" #get this
    # Sleep time (in seconds) after an error occured
    sleepTimeAfterError: 180
    # path to base dir
    baseDir: /opt/corda
