apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-generate-ambassador-certs-job
  namespace: manufacturer-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturer-generate-ambassador-certs-job
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tlscerts-gen
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    name: "manufacturer"
    metadata:
      namespace: manufacturer-quo
    image:
      initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
      certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      role: vault-role
      authpath: quorummanufacturer
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/manufacturer-quo
      retries: 30
      type: hashicorp
    subjects:
      root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
    opensslVars:
      domain_name: "manufacturer.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_api: "manufacturerapi.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_web: "manufacturerweb.saikb.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_tessera: "manufacturer-tessera.manufacturer-quo"
      clientport: 8888
