apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-ambassador-job
  namespace: carri1-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrier-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tlscert-cert-gen
    sourceRef:
      kind: GitRepository
      name: flux-bsk
      namespace: flux-bsk
  values:
    metadata:
      name: carrier-ambassador-job
      namespace: carri1-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: carrier
      clientport: 8888
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besucarri1
      rootcasecret: data/carri1-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: data/carri1-bes/crypto/carrier/tls
      role: vault-role
      serviceaccountname: vault-auth
      type: hashicorp
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: carrier.saikb.dev.aws.blockchaincloudpoc-develop.com
      domain_name_priv: carrier.carri1-bes
      domain_name_tessera: carrier-tessera.carri1-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2

    labels:
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu
