apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainpkigenerator
  namespace: supplychain-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychainpkigenerator
  interval: 1m
  chart:
   spec:
    chart: platforms/r3-corda-ent/charts/cenm-pki-gen
    sourceRef:
      kind: GitRepository
      name: flux-corddadd
      namespace: flux-corddadd
  values:
    nodeName: supplychain
    metadata:
      namespace: supplychain-ent
    image:
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      pkiContainerName: corda/enterprise-pki:1.5.1-zulu-openjdk8u242
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    acceptLicense: YES
    volume:
      baseDir: /opt/cenm
    vault:
      address: http://98.64.226.131:20001
      role: vault-role
      authpath: corddaddsupplychain
      serviceaccountname: vault-auth
      certsecretprefix: secretsv3/data/supplychain
      retries: 20
      sleepTimeAfterError: 20
    cenmServices:
      signerName: signer
      idmanName: idman
      networkmapName: networkmap
    identityManager:
      publicIp: idman.corda.blockchaincloudpoc-develop.com
      publicPort: 443
    subjects:
      tlscrlsigner: "CN=Test TLS Signer Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      tlscrlissuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
      rootca: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      subordinateca: "CN=Test Subordinate CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      idmanca: "CN=Test Identity Manager Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      networkmap: "CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    replicas: 1
    cordaJarMx: 256
    configPath: etc
