apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: v1
  namespace: sc-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: v1
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-node
    sourceRef:
      kind: GitRepository
      name: flux-bsk
      namespace: flux-bsk
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: besu
        address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
        authPath: bsksc
        secretEngine: secretsv2
        secretPrefix: "data/bsksc"
        role: vault-role
      proxy:
        provider: ambassador
        externalUrlSuffix: saikb.dev.aws.blockchaincloudpoc-develop.com
        p2p: 15040
    storage:
      enabled: true
      size: "2Gi"
    tessera:
      enabled: false
    tls:
      enabled: false
    image:
      pullSecret: regcred
      besu:
        repository: hyperledger/besu
        tag: 22.10.2
    node:
      removeKeysOnDelete: false
      isBootnode: True
      usesBootnodes: false
      besu:
        identity: v1
        envBesuOpts: ""
        resources:
          cpuLimit: 0.25
          cpuRequest: 0.05
          memLimit: "1G"
          memRequest: "300M"
        p2p:
          port: 30303
          discovery: false
        rpc:
          port: 8545
        ws:
          port: 8546
        metrics:
          enabled: True
          port: 9545
          serviceMonitorEnabled: True
        permissions:
          enabled: False #Add other permissioning params below this
