##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp # kubernetes | hashicorp

proxy:
  provider: ambassador # none | ambassador

config:
  nodeHost: member-1-substrate-node
