apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manfacturerv2quorum
  namespace: manfacturer-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manfacturerv2quorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-validator-node
    sourceRef:
      kind: GitRepository
      name: flux-sai
      namespace: flux-sai
  values:
    replicaCount: 1
    metadata:
      namespace: manfacturer-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    node:
      name: v2
      status: default
      consensus: ibft
      subject: O=v2,OU=v2,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000
    vault:
      address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
      secretprefix: secretsv2/data/manfacturer/crypto/v2
      serviceaccountname: vault-auth
      keyname: quorum
      role: vault-role
      authpath: quorummanfacturer
      type: hashicorp
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjVhZmFjYTkiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTQyYzg3Y2JlNDk3NWZmODI2NzY0YmMxOTkwN2EzYzcwYTEzNTk4YWUyOTQ1ZGVhNzFlOTc4OWJhZmQ0ZDVhZWVkN2E5NDVkYWY2YmJkNDAzOWExYjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgImdhc0xpbWl0IjogIjB4ZTAwMDAwMDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiMmM4N2NiZTQ5NzVmZjgyNjc2NGJjMTk5MDdhM2M3MGExMzU5OGFlMiI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjVkZWE3MWU5Nzg5YmFmZDRkNWFlZWQ3YTk0NWRhZjZiYmQ0MDM5YTEiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgIm51bWJlciI6ICIweDAiLAogICJnYXNVc2VkIjogIjB4MCIsCiAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes: [
    "enode://c1d46cc475accffddcb06a379a5ec6edaeae19cddd02034f58e1728593e3ba9b6ff8c97186dc588b28f9671e28274fda8160ffcd96aa7a69fda3607dc308d3e1@ca.sai29.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://cb35de881d8b42c253b80a8dfbc502328c7dbc0347438b9a9db7813a5a1bcaaedea3c80c4952db461e758c1e4e4be6c28b99059d125e1ddabb0cf3a4ecce92ce@v1.sai29.dev.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://18aa0452f3a25da2122ec6386a136888d383fa4e93ca56ac1f5f39971ab97a45d4f743a4c0173393b2b85deeeb4dd23345a3284046e150ae54533e8c2c6c9bff@ma.sai29.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0",
    "enode://e52386244808b6657ec3084401aac7a7aba9f88e7a2315d3672d88ea172c17a1a3c4697f77c4c1367556a5441f28a4ce0f6c46adfec06d502f3750e4cc9797d0@v2.sai29.dev.aws.blockchaincloudpoc-develop.com:15024?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: sai29.dev.aws.blockchaincloudpoc-develop.com
      quorumport: 15024
    storage:
      storageclassname: manfacturer-bevel-storageclass
      storagesize: 1Gi
      dbstorage: 1Gi
