- name: Create directories and set variable
  hosts: localhost
  tasks:
    - name: Set files location variable
      set_fact:
        files_loc: "{{ playbook_dir }}/../../../{{ charts_dir }}/enterprise-node/build"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ files_loc }}"
        - "{{ files_loc }}/doorman"
        - "{{ files_loc }}/nms"

    - name: Read and decode the already encoded cenm network-root-truststore.jks file
      set_fact:
        decoded_cenm_jks: "{{ lookup('file', files_loc + '/network-root-truststore.jks') | b64decode }}"

    - name: Create cenm-certs Secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cenm-certs
            namespace: "{{ component_ns }}"
          data:
            network-root-truststore.jks: "{{ decoded_cenm_jks | b64encode }}"

    - name: Read and decode the already encoded doorman tls.crt file
      set_fact:
        decoded_doorman_crt: "{{ lookup('file', files_loc + '/doorman/doorman.crt') | b64decode }}"

    - name: Create doorman-tls-certs Secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: doorman-tls-certs
            namespace: "{{ component_ns }}"
          data:
            tls.crt: "{{ decoded_doorman_crt | b64encode }}"

    - name: Read and decode the already encoded nms tls.crt file
      set_fact:
        decoded_nms_crt: "{{ lookup('file', files_loc + '/nms/tls.crt') | b64decode }}"

    - name: Create nms-tls-certs Secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: nms-tls-certs
            namespace: "{{ component_ns }}"
          data:
            tls.crt: "{{ decoded_nms_crt | b64encode }}"
