- name: Create directories for secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "./enterprise-node/build"
    - "./enterprise-node/build/doorman"
    - "./enterprise-node/build/nms"

- name: Retrieve cenm-certs secret from Kubernetes
  community.kubernetes.k8s_info:
    definition:
      apiVersion: v1
      kind: Secret
      name: cenm-certs
      namespace: supplychain-ent
  register: cenm_certs_secret

- name: Retrieve doorman-tls-certs secret from Kubernetes
  community.kubernetes.k8s_info:
    definition:
      apiVersion: v1
      kind: Secret
      name: doorman-tls-certs
      namespace: supplychain-ent
  register: doorman_tls_certs_secret

- name: Retrieve nms-tls-certs secret from Kubernetes
  community.kubernetes.k8s_info:
    definition:
      apiVersion: v1
      kind: Secret
      name: nms-tls-certs
      namespace: supplychain-ent
  register: nms_tls_certs_secret

- name: Create cenm-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cenm-certs
        namespace: manufacturer-ent
    merge_type: strategic
    merge_path: metadata.name
    merge_key: name
    data:
      network-root-truststore.jks: "{{ cenm_certs_secret.resources[0].data['network-root-truststore.jks'] }}"

- name: Create doorman-tls-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: doorman-tls-certs
        namespace: manufacturer-ent
    merge_type: strategic
    merge_path: metadata.name
    merge_key: name
    data:
      tls.crt: "{{ doorman_tls_certs_secret.resources[0].data['tls.crt'] }}"

- name: Create nms-tls-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: nms-tls-certs
        namespace: manufacturer-ent
    merge_type: strategic
    merge_path: metadata.name
    merge_key: name
    data:
      tls.crt: "{{ nms_tls_certs_secret.resources[0].data['tls.crt'] }}"