# Create deployment file for network services
- name: Create helm release file for network service
  include_role:
    name: create/helm_component
  vars:
    external_url_suffix: "{{ org.external_url_suffix }}"
    type: "{{ init_type }}"
    component_type: "Namespace"
    component_name: "{{ component_ns }}"
    doorman: "{{ org.services.doorman }}"
    nms: "{{ org.services.nms }}"

# Git Push : Pushes the above generated files to git
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing network-service files"
  tags:
    - notest