# Create deployment file for network services
- name: Create helm release file for network service
  include_role:
    name: create/helm_component
  vars:
    type: "{{ init_type }}"
    component_type: "Namespace"
  loop: node

# Git Push : Pushes the above generated files to git
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing network-service files"

- name: Check if the cenm job is completed
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: Job
    namespace: "{{ component_ns }}"
    kubernetes: "{{ organization.k8s }}"
