# Create deployment file for network services
- name: Create helm release file for network service
  include_role:
    name: create/helm_component #"{{ playbook_dir }}/../../shared/configuration/roles/create/job_component"
  vars:
    type: "{{ init_type }}"
    component_type: "Namespace"
    idman: "{{ org.services.idman }}"
    auth: "{{ org.services.auth }}"
    gateway: "{{ org.services.gateway }}"
    zone: "{{ org.services.zone }}"
  # loop: "{{ org.services }}"
  # loop_control:
  #   loop_var: node

# Git Push : Pushes the above generated files to git
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing network-service files"

# - name: Check if the cenm job is completed
#   include_role:
#     name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
#   vars:
#     component_type: Job
#     namespace: "{{ component_ns }}"
#     kubernetes: "{{ org.k8s }}"

- name: "Wait for the network services to run"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    label_selectors:
      - app.kubernetes.io/component = idman
    component_type: "pod"
    component_name: "cenm"
    namespace: "{{ component_ns }}"


# - name: "Wait for the network services  job to complete"
#   include_role:
#     name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
#   vars:
#     component_name: "cenm"
#     component_type: Job
#     namespace: "{{ component_ns }}"