name: Build Bevel

on:
  push:
    branches:
      - quoram4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: mkdir -p build

      - name: Change to Build Directory
        run: cd build

      - name: Run Docker Container
        run: |
          docker run -v $(pwd):/home/bevel/ --network="host" ghcr.io/hyperledger/bevel-build:latest
