apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrierv1quorum
  namespace: carrier-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrierv1quorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-validator-node
    sourceRef:
      kind: GitRepository
      name: flux-sai
      namespace: flux-sai
  values:
    replicaCount: 1
    metadata:
      namespace: carrier-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    node:
      name: v1
      status: default
      consensus: ibft
      subject: O=v1,OU=v1,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000
    vault:
      address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
      secretprefix: secretsv2/data/carrier/crypto/v1
      serviceaccountname: vault-auth
      keyname: quorum
      role: vault-role
      authpath: saicarrier
      type: hashicorp
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjVhZmZhOWEiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTQ3NDk3ZmYzYWE3NDc5YWE1MTVjOGI3YWQzOTNjZTNjNDQyNmM1NWJmOTRmOTRhMDhlMGYwNzFkZWQ1MDQ4YTMxZGM1N2VjNTY3NjdmOGYyNmMyYjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgImdhc0xpbWl0IjogIjB4ZTAwMDAwMDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiNzQ5N2ZmM2FhNzQ3OWFhNTE1YzhiN2FkMzkzY2UzYzQ0MjZjNTViZiI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImY5NGEwOGUwZjA3MWRlZDUwNDhhMzFkYzU3ZWM1Njc2N2Y4ZjI2YzIiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgIm51bWJlciI6ICIweDAiLAogICJnYXNVc2VkIjogIjB4MCIsCiAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes: [
    "enode://4ba318cd2608820020700a8207124b5428174100ce4cf4805a0ab9e77d19b39f22e7e9779262fa2f841f84c1c3fc7af115b273b6b56564054e8dd8c52c4055d6@ca.sai29.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://618619f8516b9efdb93d11a5de7c2e2d3bcb6a5d229b05869e489d72d1e422e4e289c3e6a800f1f66c9c546ba11b75650019779127d3ed2169b8f32b5e464f8f@v1.sai29.dev.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://92f7448374b04d0597e09de71ac00dbf2b635f896e69f5c267ad9aba6c05885cbeab0eb14b7021abdafec6aaee649ccd8a08170b033c0d343cd6220e247fa744@ma.sai29.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0",
    "enode://5cc7f268a56e18d1e20c9a89504080bfaddf8588b6708c9522fe6671d77760eeabe8a55b8c4d7f8e2e106d210ea333fba6cd765009d9fa7c7f152670bdba320c@v2.sai29.dev.aws.blockchaincloudpoc-develop.com:15024?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: sai29.dev.aws.blockchaincloudpoc-develop.com
      quorumport: 15014
    storage:
      storageclassname: carrier-bevel-storageclass
      storagesize: 1Gi
      dbstorage: 1Gi
