apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriercaonetessera
  namespace: carrier-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carriercaonetessera
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tessera-node
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    replicaCount: 1
    metadata:
      namespace: carrier-quo
      labels:
    images:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      tessera: quorumengineering/tessera:hashicorp-23.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      pullPolicy: IfNotPresent
    node:
      name: caone
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.dev.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2
      tmsecretpath: carrier-quo/crypto/caone/tm
      secretprefix: secretsv2/data/carrier-quo/crypto/caone
      serviceaccountname: vault-auth
      keyname: quorum
      role: vault-role
      authpath: quorumcarrier
      type: hashicorp
    tessera:
      dburl: "jdbc:mysql://caone-tessera:3306/demodb"
      dbusername: demouser
      url: "https://caone.saikb.dev.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://caone-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://carrier.test.quorum.blockchaincloudpoc.com
        - url: https://manufacturer.test.quorum.blockchaincloudpoc.com
        - url: https://store.test.quorum.blockchaincloudpoc.com
        - url: https://warehouse.test.quorum.blockchaincloudpoc.com
      tls: "STRICT"
      trust: "TOFU"
    proxy:
      provider: "ambassador"
      external_url: carrier.saikb.dev.aws.blockchaincloudpoc-develop.com
      clientport: 8888
    storage:
      storageclassname: carrier-aws-storageclass
      storagesize: 1Gi
      dbstorage: 1Gi
