apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-vaultk8s-job
  namespace: carrier-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    metadata:
      name: carrier-vaultk8s-job
      namespace: carrier-quo
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      role: vault-role
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      authpath: quorumcarrier
      policy: vault-crypto-carrier-quo-carrier-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/carrier-quo/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/carrier-quo/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: carrier
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://300125A3D09FFA0A178EC3522C96BBB8.gr7.eu-west-1.eks.amazonaws.com
    
    rbac:
      create: False

    serviceAccount:
      create: True
      name: vault-auth
